name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        java: ['1.8', '11', '16']
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: macos-latest
            java: '1.8'
          - os: macos-latest
            java: '16'
          - os: windows-latest
            java: '1.8'
          - os: windows-latest
            java: '16'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build
        run: |
          ./gradlew check
