name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'adopt'

      - name: Build
        run: |
          ./gradlew -i build -Pversion=${GITHUB_REF##*/v}

      - name: Release Local
        run: |
          ./gradlew -i publishAllPublicationsToLocalRepository

      - name: Release to Nexus OSS Staging
        run: |
          ./gradlew -i publishAllPublicationsToSonatypeRepository closeRepository

      - name: Release Repository
        run: |
          ./gradlew -i releaseRepository