name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Upload Release
        run: |
          ./gradlew -i \
          build \
          publishAllPublicationsToSonatypeRepository \
          -Pversion=${GITHUB_REF##*/v} \
          --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGNATORY_KEY: ${{ secrets.SIGNATORY_KEY }}
          SIGNATORY_PASSWORD: ${{ secrets.SIGNATORY_PASSWORD }}

      - name: Close and Release Repository
        run: |
          ./gradlew -i \
          closeAndReleaseRepository \
          -Pversion=${GITHUB_REF##*/v} \
          --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  announcement:
    name: "Send announcements"
    runs-on: ubuntu-latest
    needs: release
    if: success()

    steps:
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Announcement
        uses: yuzutech/zulip-send-message-action@v0.1.0
        with:
          username: ${{ secrets.ZULIP_USERNAME }}
          api-key: ${{ secrets.ZULIP_API_KEY }}
          organization-url: 'https://asciidoctor.zulipchat.com'
          to: '279652'
          type: 'stream'
          topic: 'releases'
          content: |
            asciidoctorj-chart v${{ env.RELEASE_VERSION }} is out!
            https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-chart/${{ env.RELEASE_VERSION }}/jar